### ISSUE TITLE
Just In Time Compiler Configuration Now in Core UPDATE!!

### ISSUE THREAD

**Issue by acatzk** [VeoScript/phonebox#44]
Latest features in Tailwind's new Just-in-Time engine, and walk through how to migrate from `@tailwindcss/jit` now that the new engine is available in core.

You can now Apply for mode: 'jit' in your tailwindcss configuration

**Comment by acatzk** [comment]
Here's the source https://www.youtube.com/watch?v=QwUpnXumcw4&t=224s

**Comment by VeoScript** [comment]
whoah! that's cool 😱. I'll give it a try.
